# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auvsi_suas/proto/interop_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auvsi_suas/proto/interop_api.proto',
  package='auvsi_suas.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\"auvsi_suas/proto/interop_api.proto\x12\x10\x61uvsi_suas.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t')
)




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='auvsi_suas.proto.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='auvsi_suas.proto.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='auvsi_suas.proto.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'auvsi_suas.proto.interop_api_pb2'
  # @@protoc_insertion_point(class_scope:auvsi_suas.proto.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)


# @@protoc_insertion_point(module_scope)
